In [1]:
# c'mon
import bank_functions as bf
import pandas as pd
prime_df = pd.read_excel('fully_catized_encoded_2.xlsx')
may_df = bf.clean_bank_statement_file('May21Checking.csv')

# unnecessary at this point, was meant for initial raw categorization
# may_df = bf.categorize(may_df)

may_df = bf.encode_data(may_df)
may_df['Category_Pred'] = bf.decision_tree_classifier(prime_df, may_df)

Category_Pred_Words
Dining Out                  -317.15
Entertainment               -103.63
Extra                        -30.24
Medical                       -8.00
Misc                        2942.29
Phone                        -27.00
Tolls/Uber/Metro/Parking    -554.04
Name: Amount, dtype: float64
                                           Content   Amount       Category_Pred_Words                  Category
2              VENMO/PAYMENTWALTER COLEMAN Default   -25.00                Dining Out                   Default
10             VENMO/CASHOUTWALTER COLEMAN Default    64.00                      Misc               Venmo Extra
17             VENMO/PAYMENTWALTER COLEMAN Default   -27.00                     Phone                   Default
16           USAA PC/PAYMENTWALTER COLEMAN Default  -166.05                      Misc            USAA Insurance
19    Accenture Federa/PAYRLL DEPColeman, Walter J  1937.62                      Misc                 Pay Check
18    VA DEPT TAXATION/VASTTAXRFDCOLEMAN, WALTER J    38.00                      Misc                     Extra
23          IRS TREAS 310/TAX REFCOLEMAN, WALTER J   139.32                      Misc                     Extra
25             VENMO/CASHOUTWALTER COLEMAN Default    37.70                      Misc               Venmo Extra
33             VENMO/PAYMENTWALTER COLEMAN Default   -15.00                      Misc                   Default
41             VENMO/PAYMENTWALTER COLEMAN Default   -99.29  Tolls/Uber/Metro/Parking                   Default
51       Pillar DC/Pillar DCPILLAR CHURCH OF WASHI  -310.97  Tolls/Uber/Metro/Parking                     Tithe
53             VENMO/PAYMENTWALTER COLEMAN Default   -15.00                      Misc                   Default
55    Accenture Federa/PAYRLL DEPColeman, Walter J  2099.81                      Misc                 Pay Check
62             VENMO/PAYMENTWALTER COLEMAN Default    -8.00                   Medical                   Default
0              APPLE.COM/US 800-676-2775 CA IN8800   -72.66                      Misc                      Misc
1        THE HOME DEPOT #4640 ALEXANDRIA VA062417    -30.24                     Extra                      Misc
5      SQ *IDIDOS SOCIAL HOUSE ARLINGTON VA778273     -3.30  Tolls/Uber/Metro/Parking                Dining Out
3             LEETCODE.COM HTTPSLEETCODE CA KTDFAH  -159.00                      Misc                      Misc
4        SHELL SERVICE STATION ARLINGTON VA588190    -57.39  Tolls/Uber/Metro/Parking                       Gas
6                           MIDAS. ARLINGTON VA 00   -56.00                      Misc                      Misc
8       HARRIS TEETER #3 950 S ARLINGTON VA999999    -19.26                Dining Out                 Groceries
7      ARLINGTON METER PARKING ARLINGTON VA694452     -2.25                Dining Out  Tolls/Uber/Metro/Parking
14      HARRIS TEETER #3 950 S ARLINGTON VA999999    -49.62                      Misc                 Groceries
15     HARRIS TEETER #0 4250 C ARLINGTON VA999999    -15.02                      Misc                 Groceries
9          NNT CITY KABOB 0022 ARLINGTON VA068506    -19.14                Dining Out                      Misc
13         NAZRET RESTAURANT 703-3479911 VA768720    -94.08                Dining Out                Dining Out
11       VZWRLSS*BILL PAY VE 800-9220204 CA367118    -79.12                Dining Out                      Misc
12      TST* TORTAS Y TACOS LA ARLINGTON VA310961    -13.15  Tolls/Uber/Metro/Parking                      Misc
20      HARRIS TEETER #3 950 S ARLINGTON VA999999    -35.09                      Misc                 Groceries
22               UBER EATS HELP.UBER.COM CA INC100   -29.08                      Misc                Dining Out
21  PP*GOOGLE A MEDIUM CORP 402-935-7733 CAIN1200     -4.99                      Misc             Entertainment
31     TST* GOOD COMPANY DONUT ARLINGTON VAIN7600     -9.48                      Misc                Dining Out
30      HARRIS TEETER #3 950 S ARLINGTON VA999999    -27.75                      Misc                 Groceries
24        ABM PARKING BALLSTON ARLINGTON VA952212     -1.00                      Misc  Tolls/Uber/Metro/Parking
27     HARRIS TEETER #0 4250 C ARLINGTON VA999999    -13.73                      Misc                 Groceries
28            DOMINO'S 4341 703-734-7080 VA 547982   -34.51                      Misc                      Misc
32        THE UPS STORE 4832 703-8203300 VA757409    -22.23                      Misc                      Misc
26            DOMINO'S 4341 703-734-7080 VA 547982   -19.77                      Misc                      Misc
29            DOMINO'S 4341 703-734-7080 VA 547982   -17.47             Entertainment                      Misc
34      HARRIS TEETER #3 950 S ARLINGTON VA999999    -23.91                      Misc                 Groceries
35  INOVA - HEALTH CARE SER FALLS CHURCH VA771520    -50.00                      Misc                      Misc
37     ARLINGTON METER PARKING ARLINGTON VA694452     -2.25                      Misc  Tolls/Uber/Metro/Parking
36      TST* TORTAS Y TACOS LA ARLINGTON VA648915    -14.21             Entertainment                      Misc
40      TST* TORTAS Y TACOS LA ARLINGTON VA643382    -17.11                      Misc                      Misc
42     TST* GOOD COMPANY DONUT ARLINGTON VAIN7500    -10.40                      Misc                Dining Out
38      PAYPAL *MANAGEMENTS 866-729-5327 VAIN8800    -50.00                      Misc                      Misc
39        INTUIT *TURBOTAX CL.INTUIT.COM CAIN9000   -175.00                      Misc                      Misc
43      HARRIS TEETER #3 950 S ARLINGTON VA999999    -52.44                      Misc                 Groceries
44    CKE*TOASTIQUE WASHINGTO WASHINGTON DC436559    -22.44                      Misc                      Misc
45              PUPATELLA - VA ARLINGTON VA 611494   -15.93                      Misc                Dining Out
49           SQ *PHILZ COFFEE WASHINGTON DC778273     -5.98                      Misc                Dining Out
50       PAYPAL *PARKMOBILE 402-935-7733 GAINC000     -0.45                      Misc  Tolls/Uber/Metro/Parking
47               UBER EATS HELP.UBER.COM CA IN1070   -20.00                      Misc                Dining Out
48             MANASSAS CITGO 6 MANASSAS VA 00483O   -45.28                Dining Out                       Gas
46      HARRIS TEETER #3 950 S ARLINGTON VA999999    -41.75                      Misc                 Groceries
52  INOVA - HEALTH CARE SER FALLS CHURCH VA771520    -50.00             Entertainment                      Misc
54               UBER EATS HELP.UBER.COM CA IN1200   -21.12                      Misc                Dining Out
57      HARRIS TEETER #3 950 S ARLINGTON VA999999    -18.60                      Misc                 Groceries
58      TST* TORTAS Y TACOS LA ARLINGTON VA202710    -27.08                      Misc                      Misc
59               UBER EATS HELP.UBER.COM CA INC000   -20.00                      Misc                Dining Out
56    XSPORT ARLINGTON-CKFR 877-417-1450 VA102321    -21.95             Entertainment                       Gym
60     Amazon web services aws.amazon.co WAIN0002     -2.10                Dining Out                      Misc
61  AMZN Mktp US*2L0EJ2NH1 Amzn.com/bill WAIN1200    -69.94  Tolls/Uber/Metro/Parking                      Misc
64      HARRIS TEETER #3 950 S ARLINGTON VA999999    -30.92                Dining Out                 Groceries
66       CKE*THE WHITE SPOT ATLA ATLANTA GA552585    -18.04                      Misc                      Misc
67          TST* GUAJIRO S CHARLOTTESVIL VA950102    -18.98                      Misc                      Misc
63       FARM BELL KITCHEN CHARLOTTESVIL VAINB600     -4.02                      Misc                      Misc
65               MELS CAFE CHARLOTTESVIL VA 751944   -12.68                      Misc                      Misc

In [2]:
# categorize the transactions as they actually should be
# new_df['Cat_Self_Pred'] = 'Un_catted'
# for x in range(len(new_df)):
#     print(new_df[['Content','Amount']].loc[x])
#     new_df['Cat_Self_Pred'].loc[x] = input()
# saved_cats = new_df['Cat_Self_Pred'].copy()
# new_df['Cat_Self_Pred_Num'] = new_df['Cat_Self_Pred'].apply(lambda x: word_to_num_ref[x])

# y_test = new_df['Cat_Self_Pred_Num'].to_numpy() # the real categories in numbers
# y_pred = new_predictions # the predicted categories

# # some comparison statistics
# print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
# print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
# print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

# print(new_df[['First_Word','Amount','Cat_Self_Pred']])
# print(new_df.groupby('Cat_Self_Pred')['Amount'].sum())

# Upload excel to 2021/2/or whatever budget spreadsheet
# new_df.groupby('Cat_Self_Pred')['Amount'].sum().to_excel('May21_Catized.xlsx', index=False)

word_to_num_ref:  {'Dining Out': 0, 'Entertainment': 1, 'Extra': 2, 'Gas': 3, 'Groceries': 4, 'Gym': 5, 'Medical': 6, 'Misc': 7, 'Pay Check': 8, 'Phone': 9, 'Rent': 10, 'Student Loans': 11, 'Tithe': 12, 'Tolls/Uber/Metro/Parking': 13, 'USAA Insurance': 14, 'Utilities': 15, 'Venmo Extra': 16}
word_to_num_ref type:  <class 'dict'>
Category_Pred_Words
Dining Out                   -27.10
Extra                        -30.24
Groceries                   -373.21
Misc                        2894.06
Tolls/Uber/Metro/Parking    -561.28
Name: Amount, dtype: float64
Content    APPLE.COM/US 800-676-2775 CA IN8800
Amount                                  -72.66
Name: 0, dtype: object
Misc

/Users/colemanwalterj/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

Content    THE HOME DEPOT #4640 ALEXANDRIA VA062417
Amount                                        -30.24
Name: 1, dtype: object
Misc
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -25.0
Name: 2, dtype: object
Dining Out
Content    LEETCODE.COM HTTPSLEETCODE CA KTDFAH
Amount                                   -159.0
Name: 3, dtype: object
Misc
Content    SHELL SERVICE STATION ARLINGTON VA588190
Amount                                        -57.39
Name: 4, dtype: object
Gas
Content    SQ *IDIDOS SOCIAL HOUSE ARLINGTON VA778273
Amount                                            -3.3
Name: 5, dtype: object
Dining Out
Content    MIDAS. ARLINGTON VA 00
Amount                      -56.0
Name: 6, dtype: object
Misc
Content    ARLINGTON METER PARKING ARLINGTON VA694452
Amount                                           -2.25
Name: 7, dtype: object
Tolls/Uber/Metro/Parking
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -19.26
Name: 8, dtype: object
Groceries
Content    NNT CITY KABOB 0022 ARLINGTON VA068506
Amount                                      -19.14
Name: 9, dtype: object
Dining Out
Content    VENMO/CASHOUTWALTER COLEMAN Default
Amount                                    64.0
Name: 10, dtype: object
Venmo Extra
Content    VZWRLSS*BILL PAY VE 800-9220204 CA367118
Amount                                        -79.12
Name: 11, dtype: object
Phone
Content    TST* TORTAS Y TACOS LA ARLINGTON VA310961
Amount                                         -13.15
Name: 12, dtype: object
Dining Out
Content    NAZRET RESTAURANT 703-3479911 VA768720
Amount                                      -94.08
Name: 13, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -49.62
Name: 14, dtype: object
Groceries
Content    HARRIS TEETER #0 4250 C ARLINGTON VA999999
Amount                                          -15.02
Name: 15, dtype: object
Dining Out
Content    USAA PC/PAYMENTWALTER COLEMAN Default
Amount                                   -166.05
Name: 16, dtype: object
USAA Insurance
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -27.0
Name: 17, dtype: object
Utilities
Content    VA DEPT TAXATION/VASTTAXRFDCOLEMAN, WALTER J
Amount                                             38.0
Name: 18, dtype: object
Extra
Content    Accenture Federa/PAYRLL DEPColeman, Walter J
Amount                                          1937.62
Name: 19, dtype: object
Pay Check
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -35.09
Name: 20, dtype: object
Groceries
Content    PP*GOOGLE A MEDIUM CORP 402-935-7733 CAIN1200
Amount                                              -4.99
Name: 21, dtype: object
Entertainment
Content    UBER EATS HELP.UBER.COM CA INC100
Amount                                -29.08
Name: 22, dtype: object
Dining Out
Content    IRS TREAS 310/TAX REFCOLEMAN, WALTER J
Amount                                     139.32
Name: 23, dtype: object
Extra
Content    ABM PARKING BALLSTON ARLINGTON VA952212
Amount                                         -1.0
Name: 24, dtype: object
Tolls/Uber/Metro/Parking
Content    VENMO/CASHOUTWALTER COLEMAN Default
Amount                                    37.7
Name: 25, dtype: object
Venmo Extra
Content    DOMINO'S 4341 703-734-7080 VA 547982
Amount                                   -19.77
Name: 26, dtype: object
Dining Out
Content    HARRIS TEETER #0 4250 C ARLINGTON VA999999
Amount                                          -13.73
Name: 27, dtype: object
Groceries
Content    DOMINO'S 4341 703-734-7080 VA 547982
Amount                                   -34.51
Name: 28, dtype: object
Dining Out
Content    DOMINO'S 4341 703-734-7080 VA 547982
Amount                                   -17.47
Name: 29, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -27.75
Name: 30, dtype: object
Groceries
Content    TST* GOOD COMPANY DONUT ARLINGTON VAIN7600
Amount                                           -9.48
Name: 31, dtype: object
Dining Out
Content    THE UPS STORE 4832 703-8203300 VA757409
Amount                                       -22.23
Name: 32, dtype: object
Misc
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -15.0
Name: 33, dtype: object
Utilities
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -23.91
Name: 34, dtype: object
Groceries
Content    INOVA - HEALTH CARE SER FALLS CHURCH VA771520
Amount                                              -50.0
Name: 35, dtype: object
Medical
Content    TST* TORTAS Y TACOS LA ARLINGTON VA648915
Amount                                         -14.21
Name: 36, dtype: object
Dining Out
Content    ARLINGTON METER PARKING ARLINGTON VA694452
Amount                                           -2.25
Name: 37, dtype: object
Tolls/Uber/Metro/Parking
Content    PAYPAL *MANAGEMENTS 866-729-5327 VAIN8800
Amount                                          -50.0
Name: 38, dtype: object
Misc
Content    INTUIT *TURBOTAX CL.INTUIT.COM CAIN9000
Amount                                       -175.0
Name: 39, dtype: object
Misc
Content    TST* TORTAS Y TACOS LA ARLINGTON VA643382
Amount                                         -17.11
Name: 40, dtype: object
Dining Out
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                  -99.29
Name: 41, dtype: object
Utilities
Content    TST* GOOD COMPANY DONUT ARLINGTON VAIN7500
Amount                                           -10.4
Name: 42, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -52.44
Name: 43, dtype: object
Groceries
Content    CKE*TOASTIQUE WASHINGTO WASHINGTON DC436559
Amount                                           -22.44
Name: 44, dtype: object
Dining Out
Content    PUPATELLA - VA ARLINGTON VA 611494
Amount                                 -15.93
Name: 45, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -41.75
Name: 46, dtype: object
Groceries
Content    UBER EATS HELP.UBER.COM CA IN1070
Amount                                 -20.0
Name: 47, dtype: object
Dining Out
Content    MANASSAS CITGO 6 MANASSAS VA 00483O
Amount                                  -45.28
Name: 48, dtype: object
Gas
Content    SQ *PHILZ COFFEE WASHINGTON DC778273
Amount                                     -5.98
Name: 49, dtype: object
Dining Out
Content    PAYPAL *PARKMOBILE 402-935-7733 GAINC000
Amount                                         -0.45
Name: 50, dtype: object
Tolls/Uber/Metro/Parking
Content    Pillar DC/Pillar DCPILLAR CHURCH OF WASHI
Amount                                       -310.97
Name: 51, dtype: object
Tithe
Content    INOVA - HEALTH CARE SER FALLS CHURCH VA771520
Amount                                              -50.0
Name: 52, dtype: object
Medical
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -15.0
Name: 53, dtype: object
Utilities
Content    UBER EATS HELP.UBER.COM CA IN1200
Amount                                -21.12
Name: 54, dtype: object
Dining Out
Content    Accenture Federa/PAYRLL DEPColeman, Walter J
Amount                                          2099.81
Name: 55, dtype: object
Pay Check
Content    XSPORT ARLINGTON-CKFR 877-417-1450 VA102321
Amount                                           -21.95
Name: 56, dtype: object
Gym
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                          -18.6
Name: 57, dtype: object
Groceries
Content    TST* TORTAS Y TACOS LA ARLINGTON VA202710
Amount                                         -27.08
Name: 58, dtype: object
Dining Out
Content    UBER EATS HELP.UBER.COM CA INC000
Amount                                 -20.0
Name: 59, dtype: object
Dining Out
Content    Amazon web services aws.amazon.co WAIN0002
Amount                                            -2.1
Name: 60, dtype: object

Misc
Content    AMZN Mktp US*2L0EJ2NH1 Amzn.com/bill WAIN1200
Amount                                             -69.94
Name: 61, dtype: object
Misc
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                    -8.0
Name: 62, dtype: object
Groceries
Content    FARM BELL KITCHEN CHARLOTTESVIL VAINB600
Amount                                         -4.02
Name: 63, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -30.92
Name: 64, dtype: object
Groceries
Content    MELS CAFE CHARLOTTESVIL VA 751944
Amount                                -12.68
Name: 65, dtype: object
Dining Out
Content    CKE*THE WHITE SPOT ATLA ATLANTA GA552585
Amount                                        -18.04
Name: 66, dtype: object
Dining Out
Content    TST* GUAJIRO S CHARLOTTESVIL VA950102
Amount                                     -18.98
Name: 67, dtype: object
Dining Out
Mean Absolute Error: 4.647058823529412
Mean Squared Error: 32.411764705882355
Root Mean Squared Error: 5.693133118580871
             First_Word   Amount             Cat_Self_Pred
2   VENMO/PAYMENTWALTER   -25.00                Dining Out
10  VENMO/CASHOUTWALTER    64.00               Venmo Extra
17  VENMO/PAYMENTWALTER   -27.00                 Utilities
16                 USAA  -166.05            USAA Insurance
19            Accenture  1937.62                 Pay Check
18                   VA    38.00                     Extra
23                  IRS   139.32                     Extra
25  VENMO/CASHOUTWALTER    37.70               Venmo Extra
33  VENMO/PAYMENTWALTER   -15.00                 Utilities
41  VENMO/PAYMENTWALTER   -99.29                 Utilities
51               Pillar  -310.97                     Tithe
53  VENMO/PAYMENTWALTER   -15.00                 Utilities
55            Accenture  2099.81                 Pay Check
62  VENMO/PAYMENTWALTER    -8.00                 Groceries
0          APPLE.COM/US   -72.66                      Misc
1                   THE   -30.24                      Misc
5                    SQ    -3.30                Dining Out
3          LEETCODE.COM  -159.00                      Misc
4                 SHELL   -57.39                       Gas
6                MIDAS.   -56.00                      Misc
8                HARRIS   -19.26                 Groceries
7             ARLINGTON    -2.25  Tolls/Uber/Metro/Parking
14               HARRIS   -49.62                 Groceries
15               HARRIS   -15.02                Dining Out
9                   NNT   -19.14                Dining Out
13               NAZRET   -94.08                Dining Out
11         VZWRLSS*BILL   -79.12                     Phone
12                 TST*   -13.15                Dining Out
20               HARRIS   -35.09                 Groceries
22                 UBER   -29.08                Dining Out
21            PP*GOOGLE    -4.99             Entertainment
31                 TST*    -9.48                Dining Out
30               HARRIS   -27.75                 Groceries
24                  ABM    -1.00  Tolls/Uber/Metro/Parking
27               HARRIS   -13.73                 Groceries
28             DOMINO'S   -34.51                Dining Out
32                  THE   -22.23                      Misc
26             DOMINO'S   -19.77                Dining Out
29             DOMINO'S   -17.47                Dining Out
34               HARRIS   -23.91                 Groceries
35                INOVA   -50.00                   Medical
37            ARLINGTON    -2.25  Tolls/Uber/Metro/Parking
36                 TST*   -14.21                Dining Out
40                 TST*   -17.11                Dining Out
42                 TST*   -10.40                Dining Out
38               PAYPAL   -50.00                      Misc
39               INTUIT  -175.00                      Misc
43               HARRIS   -52.44                 Groceries
44        CKE*TOASTIQUE   -22.44                Dining Out
45            PUPATELLA   -15.93                Dining Out
49                   SQ    -5.98                Dining Out
50               PAYPAL    -0.45  Tolls/Uber/Metro/Parking
47                 UBER   -20.00                Dining Out
48             MANASSAS   -45.28                       Gas
46               HARRIS   -41.75                 Groceries
52                INOVA   -50.00                   Medical
54                 UBER   -21.12                Dining Out
57               HARRIS   -18.60                 Groceries
58                 TST*   -27.08                Dining Out
59                 UBER   -20.00                Dining Out
56               XSPORT   -21.95                       Gym
60               Amazon    -2.10                      Misc
61                 AMZN   -69.94                      Misc
64               HARRIS   -30.92                 Groceries
66              CKE*THE   -18.04                Dining Out
67                 TST*   -18.98                Dining Out
63                 FARM    -4.02                Dining Out
65                 MELS   -12.68                Dining Out
Cat_Self_Pred
Dining Out                  -507.99
Entertainment                 -4.99
Extra                        177.32
Gas                         -102.67
Groceries                   -321.07
Gym                          -21.95
Medical                     -100.00
Misc                        -637.17
Pay Check                   4037.43
Phone                        -79.12
Tithe                       -310.97
Tolls/Uber/Metro/Parking      -5.95
USAA Insurance              -166.05
Utilities                   -156.29
Venmo Extra                  101.70
Name: Amount, dtype: float64

In [3]:
bf.random_forest_classifier(prime_df, may_df)

word_to_num_ref:  {'Dining Out': 0, 'Entertainment': 1, 'Extra': 2, 'Gas': 3, 'Groceries': 4, 'Gym': 5, 'Medical': 6, 'Misc': 7, 'Pay Check': 8, 'Phone': 9, 'Rent': 10, 'Student Loans': 11, 'Tithe': 12, 'Tolls/Uber/Metro/Parking': 13, 'USAA Insurance': 14, 'Utilities': 15, 'Venmo Extra': 16}
word_to_num_ref type:  <class 'dict'>
Category_Pred_Words
Dining Out                   -46.36
Extra                        -30.24
Groceries                   -373.21
Misc                        2908.33
Tolls/Uber/Metro/Parking    -556.29
Name: Amount, dtype: float64
Content    APPLE.COM/US 800-676-2775 CA IN8800
Amount                                  -72.66
Name: 0, dtype: object
Misc

/Users/colemanwalterj/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

Content    THE HOME DEPOT #4640 ALEXANDRIA VA062417
Amount                                        -30.24
Name: 1, dtype: object
Misc
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -25.0
Name: 2, dtype: object
Dining Out
Content    LEETCODE.COM HTTPSLEETCODE CA KTDFAH
Amount                                   -159.0
Name: 3, dtype: object
Misc
Content    SHELL SERVICE STATION ARLINGTON VA588190
Amount                                        -57.39
Name: 4, dtype: object
Gas
Content    SQ *IDIDOS SOCIAL HOUSE ARLINGTON VA778273
Amount                                            -3.3
Name: 5, dtype: object
Dining Out
Content    MIDAS. ARLINGTON VA 00
Amount                      -56.0
Name: 6, dtype: object
Misc
Content    ARLINGTON METER PARKING ARLINGTON VA694452
Amount                                           -2.25
Name: 7, dtype: object
Tolls/Uber/Metro/Parking
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -19.26
Name: 8, dtype: object
Groceries
Content    NNT CITY KABOB 0022 ARLINGTON VA068506
Amount                                      -19.14
Name: 9, dtype: object
Dining Out
Content    VENMO/CASHOUTWALTER COLEMAN Default
Amount                                    64.0
Name: 10, dtype: object
Venmo Extra
Content    VZWRLSS*BILL PAY VE 800-9220204 CA367118
Amount                                        -79.12
Name: 11, dtype: object
Phone
Content    TST* TORTAS Y TACOS LA ARLINGTON VA310961
Amount                                         -13.15
Name: 12, dtype: object
Dining Out
Content    NAZRET RESTAURANT 703-3479911 VA768720
Amount                                      -94.08
Name: 13, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -49.62
Name: 14, dtype: object
Groceries
Content    HARRIS TEETER #0 4250 C ARLINGTON VA999999
Amount                                          -15.02
Name: 15, dtype: object
Groceries
Content    USAA PC/PAYMENTWALTER COLEMAN Default
Amount                                   -166.05
Name: 16, dtype: object
USAA Insurance
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -27.0
Name: 17, dtype: object
Utilities
Content    VA DEPT TAXATION/VASTTAXRFDCOLEMAN, WALTER J
Amount                                             38.0
Name: 18, dtype: object
Extra
Content    Accenture Federa/PAYRLL DEPColeman, Walter J
Amount                                          1937.62
Name: 19, dtype: object
Pay Check
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -35.09
Name: 20, dtype: object
Groceries
Content    PP*GOOGLE A MEDIUM CORP 402-935-7733 CAIN1200
Amount                                              -4.99
Name: 21, dtype: object
Entertainment
Content    UBER EATS HELP.UBER.COM CA INC100
Amount                                -29.08
Name: 22, dtype: object
Dining Out
Content    IRS TREAS 310/TAX REFCOLEMAN, WALTER J
Amount                                     139.32
Name: 23, dtype: object
Extra
Content    ABM PARKING BALLSTON ARLINGTON VA952212
Amount                                         -1.0
Name: 24, dtype: object
Tolls/Uber/Metro/Parking
Content    VENMO/CASHOUTWALTER COLEMAN Default
Amount                                    37.7
Name: 25, dtype: object
Extra
Content    DOMINO'S 4341 703-734-7080 VA 547982
Amount                                   -19.77
Name: 26, dtype: object
Dining Out
Content    HARRIS TEETER #0 4250 C ARLINGTON VA999999
Amount                                          -13.73
Name: 27, dtype: object
Groceries
Content    DOMINO'S 4341 703-734-7080 VA 547982
Amount                                   -34.51
Name: 28, dtype: object
Dining Out
Content    DOMINO'S 4341 703-734-7080 VA 547982
Amount                                   -17.47
Name: 29, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -27.75
Name: 30, dtype: object
Groceries
Content    TST* GOOD COMPANY DONUT ARLINGTON VAIN7600
Amount                                           -9.48
Name: 31, dtype: object
Dining Out
Content    THE UPS STORE 4832 703-8203300 VA757409
Amount                                       -22.23
Name: 32, dtype: object
Misc
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -15.0
Name: 33, dtype: object
Utilites
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -23.91
Name: 34, dtype: object
Groceries
Content    INOVA - HEALTH CARE SER FALLS CHURCH VA771520
Amount                                              -50.0
Name: 35, dtype: object
Medical
Content    TST* TORTAS Y TACOS LA ARLINGTON VA648915
Amount                                         -14.21
Name: 36, dtype: object
Dining Out
Content    ARLINGTON METER PARKING ARLINGTON VA694452
Amount                                           -2.25
Name: 37, dtype: object
Tolls/Uber/Metro/Parking
Content    PAYPAL *MANAGEMENTS 866-729-5327 VAIN8800
Amount                                          -50.0
Name: 38, dtype: object
Misc
Content    INTUIT *TURBOTAX CL.INTUIT.COM CAIN9000
Amount                                       -175.0
Name: 39, dtype: object
Misc
Content    TST* TORTAS Y TACOS LA ARLINGTON VA643382
Amount                                         -17.11
Name: 40, dtype: object
Dining Out
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                  -99.29
Name: 41, dtype: object
Utilities
Content    TST* GOOD COMPANY DONUT ARLINGTON VAIN7500
Amount                                           -10.4
Name: 42, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -52.44
Name: 43, dtype: object
Groceries
Content    CKE*TOASTIQUE WASHINGTO WASHINGTON DC436559
Amount                                           -22.44
Name: 44, dtype: object
Dining Out
Content    PUPATELLA - VA ARLINGTON VA 611494
Amount                                 -15.93
Name: 45, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -41.75
Name: 46, dtype: object
Groceries
Content    UBER EATS HELP.UBER.COM CA IN1070
Amount                                 -20.0
Name: 47, dtype: object
Dining Out
Content    MANASSAS CITGO 6 MANASSAS VA 00483O
Amount                                  -45.28
Name: 48, dtype: object
Gas
Content    SQ *PHILZ COFFEE WASHINGTON DC778273
Amount                                     -5.98
Name: 49, dtype: object
Dining Out
Content    PAYPAL *PARKMOBILE 402-935-7733 GAINC000
Amount                                         -0.45
Name: 50, dtype: object
Tolls/Uber/Metro/Parking
Content    Pillar DC/Pillar DCPILLAR CHURCH OF WASHI
Amount                                       -310.97
Name: 51, dtype: object
Tithe
Content    INOVA - HEALTH CARE SER FALLS CHURCH VA771520
Amount                                              -50.0
Name: 52, dtype: object
Medical
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                   -15.0
Name: 53, dtype: object
Utilities
Content    UBER EATS HELP.UBER.COM CA IN1200
Amount                                -21.12
Name: 54, dtype: object
Dining Out
Content    Accenture Federa/PAYRLL DEPColeman, Walter J
Amount                                          2099.81
Name: 55, dtype: object
Pay Check
Content    XSPORT ARLINGTON-CKFR 877-417-1450 VA102321
Amount                                           -21.95
Name: 56, dtype: object
Gym
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                          -18.6
Name: 57, dtype: object
Groceries
Content    TST* TORTAS Y TACOS LA ARLINGTON VA202710
Amount                                         -27.08
Name: 58, dtype: object
Dining Out
Content    UBER EATS HELP.UBER.COM CA INC000
Amount                                 -20.0
Name: 59, dtype: object
Dining Out
Content    Amazon web services aws.amazon.co WAIN0002
Amount                                            -2.1
Name: 60, dtype: object

Misc
Content    AMZN Mktp US*2L0EJ2NH1 Amzn.com/bill WAIN1200
Amount                                             -69.94
Name: 61, dtype: object
Misc
Content    VENMO/PAYMENTWALTER COLEMAN Default
Amount                                    -8.0
Name: 62, dtype: object
Groceries
Content    FARM BELL KITCHEN CHARLOTTESVIL VAINB600
Amount                                         -4.02
Name: 63, dtype: object
Dining Out
Content    HARRIS TEETER #3 950 S ARLINGTON VA999999
Amount                                         -30.92
Name: 64, dtype: object
Groceries
Content    MELS CAFE CHARLOTTESVIL VA 751944
Amount                                -12.68
Name: 65, dtype: object
Dining Out
Content    CKE*THE WHITE SPOT ATLA ATLANTA GA552585
Amount                                        -18.04
Name: 66, dtype: object
Dining Out
Content    TST* GUAJIRO S CHARLOTTESVIL VA950102
Amount                                     -18.98
Name: 67, dtype: object
Dining Out

KeyError: 'Utilites'

In [4]:
saved_cats

NameError: name 'saved_cats' is not defined

In [3]:
import os
os.getcwd()

'/Users/colemanwalterj/Documents/BankStatementCategorizer/BankParser'

In [5]:
os.listdir()

['DecemberChecking.csv',
 'new toggling.ipynb',
 'DecemberAnalysis.ipynb',
 'clean_categorize_code.ipynb',
 'May15_2021_Checking.csv',
 'Scatch Code',
 'Pillar_DC_donations.csv',
 '.DS_Store',
 'May21Checking.csv',
 'Atwork.ipynb',
 'CleanedStatements',
 'Apr21_NedBetCat.xlsx',
 'Untitled.ipynb',
 'Dec_Jan_21_venmo_statement.csv',
 'FebruaryFormatted.xlsx',
 'Fin_Statement.ipynb',
 'Create Purchase Date.ipynb',
 'March2021.csv',
 'venmo_defaults.csv',
 'OctoberChecking.csv',
 'MarchChecking.csv',
 'tests',
 'Theil U, Random Forest, cross-validation analysis for February failed, but columns created, decoding failed.ipynb',
 'ExcelUploadTest.xlsx',
 'SeptemberChecking.csv',
 'March21_NeedBettCatzn.xlsx',
 'Atlantic Union.ipynb',
 'test_results3.xlsx',
 '__pycache__',
 'JuneChecking.csv',
 'Fix_real_quick.xlsx',
 'JanuaryChecking.csv',
 'Encoding for decision tree.ipynb',
 'MonthlyExpenditure.png',
 'AprilChecking.csv',
 'Compile and Label.ipynb',
 'Test and further analysis June 8 2021.ipynb',
 'FebruaryChecking.csv',
 'Classes.ipynb',
 'bank_statements_categorized.xlsx',
 'Feb & Mar 21 Analysis.ipynb',
 'fully_catized_fully_encoded.xlsx',
 'Feb26FinalVersion.xlsx',
 '.ipynb_checkpoints',
 'AugustChecking.csv',
 'Categorize remaining Feb26 defaults.ipynb',
 'April21Check.csv',
 '.git',
 'May halfway analysis.ipynb',
 'Functions Created, Encoder, Random Forest first attempt.ipynb',
 'JulyChecking.csv',
 'bank_functions.py',
 'MayChecking.csv',
 'Partial Statements',
 'Clean & Categorize, function creation and data visuals.ipynb',
 'tree.dot',
 '.idea']